version: "3.9"

services:
  orchestrator:
    build: "./orchestrator"
    ports:
      - "80:80"
    environment:
      - "USERS_URL=http://users:8080"
      - "PRODUCTS_URL=http://products:8880"
  users:
    build: "./services/users"
    ports:
      - "8080:8080"
  products:
    build: "./services/products"
    ports:
      - "8880:8880"
